# 2.1 Combining Commuter and Transit Datasets

### This script contains the following:

#### 1. Importing libraries and data
#### 2. Merge commuter datasets
#### 3. Merge transit datasets 
#### 4. Combine commuter and transit datasets
#### 5. Export combined commuter and transit dataframe

## 1. Importing libraries and data

In [1]:
# import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# set up path variable for easy import and export of data

path = '/Users/matthewmacbook/Documents/CareerFoundry/Data Immersion/Achievement 6 - Advanced Analytics and Dashboard Design/COVID-19 Public Transit Project'

In [3]:
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 100)

In [4]:
low_memory = False

In [5]:
# Import commuter datasets
df_commute_modeshare = pd.read_csv(os.path.join(path, 'Datasets', 'Clean Data', 'commute_modeshare_2018_to_2022.csv'))
df_commute_time = pd.read_csv(os.path.join(path, 'Datasets', 'Clean Data', 'commute_time_2018_to_2022.csv'))
df_depart_time = pd.read_csv(os.path.join(path, 'Datasets', 'Clean Data', 'depart_time_2018_to_2022.csv'))
df_household_vehicles = pd.read_csv(os.path.join(path, 'Datasets', 'Clean Data', 'household_vehicles_2018_to_2022.csv'))
df_place_of_work = pd.read_csv(os.path.join(path, 'Datasets', 'Clean Data', 'place_of_work_2018_to_2022.csv'))

# Import transit datasets
df_trips = pd.read_csv(os.path.join(path, 'Datasets', 'Clean Data', 'trips_2018_to_2023.csv'))
df_vehicle_miles = pd.read_csv(os.path.join(path, 'Datasets', 'Clean Data', 'vehicle_miles_2018_to_2023.csv'))

## 2. Merge commuter datasets 
#### In order to get UACE Codes from commuter datasets, must split 'Geography' column and retain last 5 digits as UACE code.

Note: the UACE codes in the transit datasets do not contain the leading zeroes (ex. Boston should be "09271" but is "9271" within the transit datasets' 'UACE CD' column) <br>
This will need to be worked around as well.

In [6]:
# Define a list of dataframes to merge
dataframes_to_merge = [df_commute_modeshare, df_commute_time, df_depart_time, df_household_vehicles, df_place_of_work]

# Initialize the merged dataframe with the first dataframe
df_commuter = dataframes_to_merge[0]

# Merge the dataframes using a loop, specifying the merge columns
for i, df in enumerate(dataframes_to_merge[1:], start=1):
    df_commuter = pd.merge(df_commuter, df, on=['Geography', 'Geographic Area Name', 'Year'])

df_commuter

,Geography,Geographic Area Name,Year,"Commute by Car, Truck, or Van",Commute by Drove alone,Commute by Carpooled,Commute by 2-person Carpool,Commute by 3-person Carpool,Commute by 4-or-more-person Carpool,Average Number of Workers per Car,Commute by Public Transportation,Commute by Walking,Commute by Bicycle,"Commute by Taxicab, Motorcycle, or Other means",Commute by Work from Home,Commute Time <10 Minutes,Commute Time 10 to 14 Minutes,Commute Time 15 to 19 Minutes,Commute Time 20 to 24 Minutes,Commute Time 25 to 29 Minutes,Commute Time 30 to 34 Minutes,Commute Time 35 to 44 Minutes,Commute Time 45 to 59 Minutes,Commute Time >60 Minutes,Mean Commute Time,Depart Time 12:00 a.m. to 4:59 a.m.,Depart Time 5:00 a.m. to 5:29 a.m.,Depart Time 5:30 a.m. to 5:59 a.m.,Depart Time 6:00 a.m. to 6:29 a.m.,Depart Time 6:30 a.m. to 6:59 a.m.,Depart Time 7:00 a.m. to 7:29 a.m.,Depart Time 7:30 a.m. to 7:59 a.m.,Depart Time 8:00 a.m. to 8:29 a.m.,Depart Time 8:30 a.m. to 8:59 a.m.,Depart Time 9:00 a.m. to 11:59 p.m.,Workers 16 Years and Over in Households,Households with 0 Vehicles available,Households with 1 Vehicle Available,Households with 2 Vehicles Available,Households with 3 or More Vehicles Available,Worked in State of Residence,Worked in County of Residence,Worked Outside County of Residence,Worked Outside State of Residence,Living in a Place,Worked in Place of Residence,Worked Outside Place of Residence,Not living in a place
0,400C100US00199,"Aberdeen--Bel Air South--Bel Air North, MD Urb...",2018,93.0,85.6,7.4,6.2,0.6,0.6,1.04,0.9,0.9,0.1,0.6,4.5,9.5,12.0,11.7,10.7,5.3,14.8,9.4,13.5,13.2,31.5,5.7,4.1,5.7,11.6,10.2,14.4,12.9,9.2,6.1,20.3,115253,1.2,14.3,40.8,43.6,96.4,52.9,43.5,3.6,85.1,13.1,72.0,14.9
1,400C100US00280,"Abilene, TX Urbanized Area (2010)",2018,91.3,76.7,14.6,10.3,2.3,2.0,1.1,0.1,1.6,0.0,1.2,5.7,24.8,29.7,26.2,11.0,0.5,3.4,0.7,1.2,2.6,15.2,5.5,2.4,5.0,4.1,9.1,13.7,20.0,8.4,6.2,25.4,54675,2.9,27.3,46.2,23.6,99.8,94.0,5.8,0.2,99.6,88.7,10.9,0.4
2,400C100US00631,"Aguadilla--Isabela--San Sebastián, PR Urbanize...",2018,93.6,85.6,8.0,6.1,1.0,0.8,1.05,0.2,2.0,1.0,1.2,2.0,16.4,12.1,17.4,12.5,7.3,9.5,7.0,6.2,11.5,26.3,6.7,4.3,3.4,13.2,12.2,22.7,8.8,8.9,1.7,18.1,71908,4.2,29.2,42.5,24.2,99.4,51.2,48.2,0.6,22.8,8.7,14.0,77.2
3,400C100US00766,"Akron, OH Urbanized Area (2010)",2018,90.1,82.4,7.7,5.5,1.3,0.8,1.05,2.0,2.0,0.3,0.6,5.1,12.5,15.2,16.4,17.9,9.4,12.1,6.3,6.1,4.2,23.1,3.4,2.9,5.3,9.1,11.5,14.6,11.6,10.2,5.0,26.4,272448,4.0,19.6,45.2,31.2,99.4,70.9,28.5,0.6,84.9,26.4,58.5,15.1
4,400C100US00970,"Albany--Schenectady, NY Urbanized Area (2010)",2018,85.4,76.9,8.5,6.9,1.0,0.5,1.06,5.0,4.3,0.3,1.1,3.9,13.0,14.8,19.9,18.4,9.0,13.0,4.4,4.3,3.2,21.6,3.5,1.7,2.7,6.2,9.9,15.1,15.1,13.8,7.6,24.5,293812,6.4,24.0,43.3,26.3,99.2,63.3,35.9,0.8,55.2,18.3,36.9,44.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,400C200US97507,"Yakima, WA Urban Area (2020)",2022,89.5,80.1,9.4,7.4,0.6,1.4,1.06,0.2,1.2,0.3,0.9,7.9,20.3,20.8,22.5,14.4,5.0,7.4,3.7,2.1,3.9,18.4,6.6,5.9,7.7,10.8,10.8,13.8,14.0,6.1,2.3,21.8,56289,1.7,17.3,34.7,46.3,99.9,96.3,3.7,0.1,93.7,49.8,44.0,6.3
5014,400C200US97750,"York, PA Urban Area (2020)",2022,83.4,75.6,7.8,6.5,1.0,0.2,1.05,0.8,1.2,0.2,1.7,12.6,10.5,18.7,17.5,15.0,6.0,10.8,5.8,8.1,7.6,25.3,7.5,3.6,6.8,11.5,10.4,13.0,10.9,7.4,4.6,24.5,120099,2.4,17.6,44.7,35.2,94.4,82.0,12.4,5.6,60.7,12.8,47.9,39.3
5015,400C200US97831,"Youngstown, OH Urban Area (2020)",2022,89.3,81.5,7.8,5.9,1.0,0.9,1.05,0.5,1.7,0.2,1.1,7.2,16.2,17.0,20.0,17.0,6.9,9.7,4.3,3.8,5.1,21.6,4.9,4.2,4.8,6.9,8.1,13.0,11.6,11.3,5.7,29.5,141374,2.3,23.8,43.0,30.9,94.1,69.9,24.2,5.9,69.2,17.0,52.2,30.8
5016,400C200US97939,"Yuba City, CA Urban Area (2020)",2022,89.6,75.6,14.0,8.2,1.2,4.6,1.1,0.3,1.1,0.8,1.6,6.6,14.0,15.3,12.0,8.5,2.2,10.5,9.1,15.9,12.4,31.0,9.5,10.6,5.4,9.3,10.3,11.2,11.3,9.7,3.0,19.7,53027,4.0,12.6,34.2,49.1,99.4,48.1,51.3,0.6,93.4,30.0,63.3,6.6
5017,400C200US98020,"Yuma, AZ--CA Urban Area (2020)",2022,87.0,77.8,9.2,5.8,1.7,1.8,1.07,0.2,2.3,0.3,1.0,9.1,14.8,19.4,22.8,19.4,2.6,11.4,2.6,3.6,3.3,19.4,9.0,9.8,9.1,8.8,10.7,13.3,8.8,5.0,2.3,23.1,51855,2.9,19.9,42.2,35.0,92.1,91.7,0.4,7.9,95.0,58.9,36.1,5.0

In [7]:
df_commuter.dtypes

Geography                                          object
Geographic Area Name                               object
Year                                                int64
Commute by Car, Truck, or Van                     float64
Commute by Drove alone                            float64
Commute by Carpooled                              float64
Commute by 2-person Carpool                       float64
Commute by 3-person Carpool                       float64
Commute by 4-or-more-person Carpool               float64
Average Number of Workers per Car                  object
Commute by Public Transportation                  float64
Commute by Walking                                float64
Commute by Bicycle                                float64
Commute by Taxicab, Motorcycle, or Other means    float64
Commute by Work from Home                         float64
Commute Time <10 Minutes                          float64
Commute Time 10 to 14 Minutes                     float64
Commute Time 15 to 19 Minutes                     float64
Commute Time 20 to 24 Minutes                     float64
Commute Time 25 to 29 Minutes                     float64
Commute Time 30 to 34 Minutes                     float64
Commute Time 35 to 44 Minutes                     float64
Commute Time 45 to 59 Minutes                     float64
Commute Time >60 Minutes                          float64
Mean Commute Time                                 float64
Depart Time 12:00 a.m. to 4:59 a.m.               float64
Depart Time 5:00 a.m. to 5:29 a.m.                float64
Depart Time 5:30 a.m. to 5:59 a.m.                float64
Depart Time 6:00 a.m. to 6:29 a.m.                float64
Depart Time 6:30 a.m. to 6:59 a.m.                float64
Depart Time 7:00 a.m. to 7:29 a.m.                float64
Depart Time 7:30 a.m. to 7:59 a.m.                float64
Depart Time 8:00 a.m. to 8:29 a.m.                float64
Depart Time 8:30 a.m. to 8:59 a.m.                float64
Depart Time 9:00 a.m. to 11:59 p.m.               float64
Workers 16 Years and Over in Households             int64
Households with 0 Vehicles available              float64
Households with 1 Vehicle Available               float64
Households with 2 Vehicles Available              float64
Households with 3 or More Vehicles Available      float64
Worked in State of Residence                      float64
Worked in County of Residence                     float64
Worked Outside County of Residence                float64
Worked Outside State of Residence                 float64
Living in a Place                                 float64
Worked in Place of Residence                      float64
Worked Outside Place of Residence                 float64
Not living in a place                             float64
dtype: object

In [8]:
# Convert 'Average Number of Workers per Car' column to float
df_commuter['Average Number of Workers per Car'] = pd.to_numeric(df_commuter['Average Number of Workers per Car'], errors='coerce')

#### Check for Missing Values

In [9]:
# Check for missing values

df_commuter.isnull().sum()

Geography                                         0
Geographic Area Name                              0
Year                                              0
Commute by Car, Truck, or Van                     0
Commute by Drove alone                            0
Commute by Carpooled                              0
Commute by 2-person Carpool                       0
Commute by 3-person Carpool                       0
Commute by 4-or-more-person Carpool               0
Average Number of Workers per Car                 1
Commute by Public Transportation                  0
Commute by Walking                                0
Commute by Bicycle                                0
Commute by Taxicab, Motorcycle, or Other means    0
Commute by Work from Home                         0
Commute Time <10 Minutes                          0
Commute Time 10 to 14 Minutes                     0
Commute Time 15 to 19 Minutes                     0
Commute Time 20 to 24 Minutes                     0
Commute Time 25 to 29 Minutes                     0
Commute Time 30 to 34 Minutes                     0
Commute Time 35 to 44 Minutes                     0
Commute Time 45 to 59 Minutes                     0
Commute Time >60 Minutes                          0
Mean Commute Time                                 0
Depart Time 12:00 a.m. to 4:59 a.m.               0
Depart Time 5:00 a.m. to 5:29 a.m.                0
Depart Time 5:30 a.m. to 5:59 a.m.                0
Depart Time 6:00 a.m. to 6:29 a.m.                0
Depart Time 6:30 a.m. to 6:59 a.m.                0
Depart Time 7:00 a.m. to 7:29 a.m.                0
Depart Time 7:30 a.m. to 7:59 a.m.                0
Depart Time 8:00 a.m. to 8:29 a.m.                0
Depart Time 8:30 a.m. to 8:59 a.m.                0
Depart Time 9:00 a.m. to 11:59 p.m.               0
Workers 16 Years and Over in Households           0
Households with 0 Vehicles available              0
Households with 1 Vehicle Available               0
Households with 2 Vehicles Available              0
Households with 3 or More Vehicles Available      0
Worked in State of Residence                      0
Worked in County of Residence                     0
Worked Outside County of Residence                0
Worked Outside State of Residence                 0
Living in a Place                                 0
Worked in Place of Residence                      0
Worked Outside Place of Residence                 0
Not living in a place                             0
dtype: int64

In [10]:
df_commuter.dropna(inplace = True)

In [11]:
# Check for missing values

df_commuter.isnull().sum()

Geography                                         0
Geographic Area Name                              0
Year                                              0
Commute by Car, Truck, or Van                     0
Commute by Drove alone                            0
Commute by Carpooled                              0
Commute by 2-person Carpool                       0
Commute by 3-person Carpool                       0
Commute by 4-or-more-person Carpool               0
Average Number of Workers per Car                 0
Commute by Public Transportation                  0
Commute by Walking                                0
Commute by Bicycle                                0
Commute by Taxicab, Motorcycle, or Other means    0
Commute by Work from Home                         0
Commute Time <10 Minutes                          0
Commute Time 10 to 14 Minutes                     0
Commute Time 15 to 19 Minutes                     0
Commute Time 20 to 24 Minutes                     0
Commute Time 25 to 29 Minutes                     0
Commute Time 30 to 34 Minutes                     0
Commute Time 35 to 44 Minutes                     0
Commute Time 45 to 59 Minutes                     0
Commute Time >60 Minutes                          0
Mean Commute Time                                 0
Depart Time 12:00 a.m. to 4:59 a.m.               0
Depart Time 5:00 a.m. to 5:29 a.m.                0
Depart Time 5:30 a.m. to 5:59 a.m.                0
Depart Time 6:00 a.m. to 6:29 a.m.                0
Depart Time 6:30 a.m. to 6:59 a.m.                0
Depart Time 7:00 a.m. to 7:29 a.m.                0
Depart Time 7:30 a.m. to 7:59 a.m.                0
Depart Time 8:00 a.m. to 8:29 a.m.                0
Depart Time 8:30 a.m. to 8:59 a.m.                0
Depart Time 9:00 a.m. to 11:59 p.m.               0
Workers 16 Years and Over in Households           0
Households with 0 Vehicles available              0
Households with 1 Vehicle Available               0
Households with 2 Vehicles Available              0
Households with 3 or More Vehicles Available      0
Worked in State of Residence                      0
Worked in County of Residence                     0
Worked Outside County of Residence                0
Worked Outside State of Residence                 0
Living in a Place                                 0
Worked in Place of Residence                      0
Worked Outside Place of Residence                 0
Not living in a place                             0
dtype: int64

#### Check for Duplicates

In [12]:
# Find duplicates

df_commuter_dups = df_commuter[df_commuter.duplicated()]

In [13]:
df_commuter_dups.shape # No duplicates!

(0, 48)

#### Check for Mixed-Type Data:

In [14]:
for col in df_commuter.columns.tolist():
      weird = (df_commuter[[col]].applymap(type) != df_commuter[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df_commuter[weird]) > 0:
        print (col)
        
# No mixed-type columns

### Split 'Geography' column to create 'UACE CD' column

In [15]:
# Create a new column 'UACE Code' with the last 5 characters
df_commuter['UACE Code'] = df_commuter['Geography'].str[-5:]

df_commuter

,Geography,Geographic Area Name,Year,"Commute by Car, Truck, or Van",Commute by Drove alone,Commute by Carpooled,Commute by 2-person Carpool,Commute by 3-person Carpool,Commute by 4-or-more-person Carpool,Average Number of Workers per Car,Commute by Public Transportation,Commute by Walking,Commute by Bicycle,"Commute by Taxicab, Motorcycle, or Other means",Commute by Work from Home,Commute Time <10 Minutes,Commute Time 10 to 14 Minutes,Commute Time 15 to 19 Minutes,Commute Time 20 to 24 Minutes,Commute Time 25 to 29 Minutes,Commute Time 30 to 34 Minutes,Commute Time 35 to 44 Minutes,Commute Time 45 to 59 Minutes,Commute Time >60 Minutes,Mean Commute Time,Depart Time 12:00 a.m. to 4:59 a.m.,Depart Time 5:00 a.m. to 5:29 a.m.,Depart Time 5:30 a.m. to 5:59 a.m.,Depart Time 6:00 a.m. to 6:29 a.m.,Depart Time 6:30 a.m. to 6:59 a.m.,Depart Time 7:00 a.m. to 7:29 a.m.,Depart Time 7:30 a.m. to 7:59 a.m.,Depart Time 8:00 a.m. to 8:29 a.m.,Depart Time 8:30 a.m. to 8:59 a.m.,Depart Time 9:00 a.m. to 11:59 p.m.,Workers 16 Years and Over in Households,Households with 0 Vehicles available,Households with 1 Vehicle Available,Households with 2 Vehicles Available,Households with 3 or More Vehicles Available,Worked in State of Residence,Worked in County of Residence,Worked Outside County of Residence,Worked Outside State of Residence,Living in a Place,Worked in Place of Residence,Worked Outside Place of Residence,Not living in a place,UACE Code
0,400C100US00199,"Aberdeen--Bel Air South--Bel Air North, MD Urb...",2018,93.0,85.6,7.4,6.2,0.6,0.6,1.04,0.9,0.9,0.1,0.6,4.5,9.5,12.0,11.7,10.7,5.3,14.8,9.4,13.5,13.2,31.5,5.7,4.1,5.7,11.6,10.2,14.4,12.9,9.2,6.1,20.3,115253,1.2,14.3,40.8,43.6,96.4,52.9,43.5,3.6,85.1,13.1,72.0,14.9,00199
1,400C100US00280,"Abilene, TX Urbanized Area (2010)",2018,91.3,76.7,14.6,10.3,2.3,2.0,1.10,0.1,1.6,0.0,1.2,5.7,24.8,29.7,26.2,11.0,0.5,3.4,0.7,1.2,2.6,15.2,5.5,2.4,5.0,4.1,9.1,13.7,20.0,8.4,6.2,25.4,54675,2.9,27.3,46.2,23.6,99.8,94.0,5.8,0.2,99.6,88.7,10.9,0.4,00280
2,400C100US00631,"Aguadilla--Isabela--San Sebastián, PR Urbanize...",2018,93.6,85.6,8.0,6.1,1.0,0.8,1.05,0.2,2.0,1.0,1.2,2.0,16.4,12.1,17.4,12.5,7.3,9.5,7.0,6.2,11.5,26.3,6.7,4.3,3.4,13.2,12.2,22.7,8.8,8.9,1.7,18.1,71908,4.2,29.2,42.5,24.2,99.4,51.2,48.2,0.6,22.8,8.7,14.0,77.2,00631
3,400C100US00766,"Akron, OH Urbanized Area (2010)",2018,90.1,82.4,7.7,5.5,1.3,0.8,1.05,2.0,2.0,0.3,0.6,5.1,12.5,15.2,16.4,17.9,9.4,12.1,6.3,6.1,4.2,23.1,3.4,2.9,5.3,9.1,11.5,14.6,11.6,10.2,5.0,26.4,272448,4.0,19.6,45.2,31.2,99.4,70.9,28.5,0.6,84.9,26.4,58.5,15.1,00766
4,400C100US00970,"Albany--Schenectady, NY Urbanized Area (2010)",2018,85.4,76.9,8.5,6.9,1.0,0.5,1.06,5.0,4.3,0.3,1.1,3.9,13.0,14.8,19.9,18.4,9.0,13.0,4.4,4.3,3.2,21.6,3.5,1.7,2.7,6.2,9.9,15.1,15.1,13.8,7.6,24.5,293812,6.4,24.0,43.3,26.3,99.2,63.3,35.9,0.8,55.2,18.3,36.9,44.8,00970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,400C200US97507,"Yakima, WA Urban Area (2020)",2022,89.5,80.1,9.4,7.4,0.6,1.4,1.06,0.2,1.2,0.3,0.9,7.9,20.3,20.8,22.5,14.4,5.0,7.4,3.7,2.1,3.9,18.4,6.6,5.9,7.7,10.8,10.8,13.8,14.0,6.1,2.3,21.8,56289,1.7,17.3,34.7,46.3,99.9,96.3,3.7,0.1,93.7,49.8,44.0,6.3,97507
5014,400C200US97750,"York, PA Urban Area (2020)",2022,83.4,75.6,7.8,6.5,1.0,0.2,1.05,0.8,1.2,0.2,1.7,12.6,10.5,18.7,17.5,15.0,6.0,10.8,5.8,8.1,7.6,25.3,7.5,3.6,6.8,11.5,10.4,13.0,10.9,7.4,4.6,24.5,120099,2.4,17.6,44.7,35.2,94.4,82.0,12.4,5.6,60.7,12.8,47.9,39.3,97750
5015,400C200US97831,"Youngstown, OH Urban Area (2020)",2022,89.3,81.5,7.8,5.9,1.0,0.9,1.05,0.5,1.7,0.2,1.1,7.2,16.2,17.0,20.0,17.0,6.9,9.7,4.3,3.8,5.1,21.6,4.9,4.2,4.8,6.9,8.1,13.0,11.6,11.3,5.7,29.5,141374,2.3,23.8,43.0,30.9,94.1,69.9,24.2,5.9,69.2,17.0,52.2,30.8,97831
5016,400C200US97939,"Yuba City, CA Urban Area (2020)",2022,89.6,75.6,14.0,8.2,1.2,4.6,1.10,0.3,1.1,0.8,1.6,6.6,14.0,15.3,12.0,8.5,2.2,10.5,9.1,15.9,12.4,31.0,9.5,10.6,5.4,9.3,10.3,11.2,11.3,9.7,3.0,19.7,53027,4.0,12.6,34.2,49.1,99.4,48.1,51.3,0.6,93.4,30.0,63.3,6.6,97939
5017,400C200US98020,"Yuma, AZ--CA Urban Area (2020)",2022,87.0,77.8,9.2,5.8,1.7,1.8,1.07,0.2,2.3,0.3,1.0,9.1,14.8,19.4,22.8,19.4,2.6,11.4,2.6,3.6,3.3,19.4,9.0,9.8,9.1,8.8,10.7,13.3,8.8,5.0,2.3,23.1,51855,2.9,19.9,42.2,35.0,92.1,91.7,0.4,7.9,95.0,58.9,36.1,5.0,98020

In [16]:
df_commuter.dtypes

Geography                                          object
Geographic Area Name                               object
Year                                                int64
Commute by Car, Truck, or Van                     float64
Commute by Drove alone                            float64
Commute by Carpooled                              float64
Commute by 2-person Carpool                       float64
Commute by 3-person Carpool                       float64
Commute by 4-or-more-person Carpool               float64
Average Number of Workers per Car                 float64
Commute by Public Transportation                  float64
Commute by Walking                                float64
Commute by Bicycle                                float64
Commute by Taxicab, Motorcycle, or Other means    float64
Commute by Work from Home                         float64
Commute Time <10 Minutes                          float64
Commute Time 10 to 14 Minutes                     float64
Commute Time 15 to 19 Minutes                     float64
Commute Time 20 to 24 Minutes                     float64
Commute Time 25 to 29 Minutes                     float64
Commute Time 30 to 34 Minutes                     float64
Commute Time 35 to 44 Minutes                     float64
Commute Time 45 to 59 Minutes                     float64
Commute Time >60 Minutes                          float64
Mean Commute Time                                 float64
Depart Time 12:00 a.m. to 4:59 a.m.               float64
Depart Time 5:00 a.m. to 5:29 a.m.                float64
Depart Time 5:30 a.m. to 5:59 a.m.                float64
Depart Time 6:00 a.m. to 6:29 a.m.                float64
Depart Time 6:30 a.m. to 6:59 a.m.                float64
Depart Time 7:00 a.m. to 7:29 a.m.                float64
Depart Time 7:30 a.m. to 7:59 a.m.                float64
Depart Time 8:00 a.m. to 8:29 a.m.                float64
Depart Time 8:30 a.m. to 8:59 a.m.                float64
Depart Time 9:00 a.m. to 11:59 p.m.               float64
Workers 16 Years and Over in Households             int64
Households with 0 Vehicles available              float64
Households with 1 Vehicle Available               float64
Households with 2 Vehicles Available              float64
Households with 3 or More Vehicles Available      float64
Worked in State of Residence                      float64
Worked in County of Residence                     float64
Worked Outside County of Residence                float64
Worked Outside State of Residence                 float64
Living in a Place                                 float64
Worked in Place of Residence                      float64
Worked Outside Place of Residence                 float64
Not living in a place                             float64
UACE Code                                          object
dtype: object

## 3. Merge transit datasets

In [17]:
df_trips

,NTD ID,Agency,Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,2018,2019,2020,2021,2022,2023
0,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,PT,Bus,883312,887915,455391,468104,552215,400306
1,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,TN,Bus,0,0,0,0,0,150541
2,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,TX,Bus,143747,177791,86460,88944,110794,82622
3,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,664365,701608,146930,286843,400407,286634
4,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",LR,DO,Rail,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2255,99423,City of Glendale,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",MB,PT,Bus,1431136,1414940,529112,418715,624155,509462
2256,99424,City of Pasadena,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,PT,Bus,86218,90957,38581,35436,38412,37337
2257,99424,City of Pasadena,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",MB,PT,Bus,1508413,1526844,957115,931575,1139100,710151
2258,99425,Pomona Valley Transportation Authority,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,PT,Bus,84088,84110,30654,41567,57862,45972
2259,99425,Pomona Valley Transportation Authority,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,TX,Bus,68805,63067,37262,23044,18194,13090

In [18]:
# Rename df_trips years columns into 'Trips 2018' and so on

# Define the new column names
column_mapping = {
    '2018': 'Trips 2018',
    '2019': 'Trips 2019',
    '2020': 'Trips 2020',
    '2021': 'Trips 2021',
    '2022': 'Trips 2022',
    '2023': 'Trips 2023'
}

# Use column mapping to rename df_trips column headers
df_trips.rename(columns=column_mapping, inplace = True)

In [19]:
df_trips

,NTD ID,Agency,Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,Trips 2018,Trips 2019,Trips 2020,Trips 2021,Trips 2022,Trips 2023
0,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,PT,Bus,883312,887915,455391,468104,552215,400306
1,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,TN,Bus,0,0,0,0,0,150541
2,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,TX,Bus,143747,177791,86460,88944,110794,82622
3,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,664365,701608,146930,286843,400407,286634
4,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",LR,DO,Rail,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2255,99423,City of Glendale,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",MB,PT,Bus,1431136,1414940,529112,418715,624155,509462
2256,99424,City of Pasadena,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,PT,Bus,86218,90957,38581,35436,38412,37337
2257,99424,City of Pasadena,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",MB,PT,Bus,1508413,1526844,957115,931575,1139100,710151
2258,99425,Pomona Valley Transportation Authority,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,PT,Bus,84088,84110,30654,41567,57862,45972
2259,99425,Pomona Valley Transportation Authority,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,TX,Bus,68805,63067,37262,23044,18194,13090

In [20]:
# Rename df_vehicle_miles years columns into 'Vehicle Miles 2018' and so on

# Define the new column names
column_mapping = {
    '2018': 'Vehicle Miles 2018',
    '2019': 'Vehicle Miles 2019',
    '2020': 'Vehicle Miles 2020',
    '2021': 'Vehicle Miles 2021',
    '2022': 'Vehicle Miles 2022',
    '2023': 'Vehicle Miles 2023'
}

# Use column mapping to rename df_trips column headers
df_vehicle_miles.rename(columns=column_mapping, inplace = True)

In [21]:
df_vehicle_miles

,NTD ID,Agency,Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,Vehicle Miles 2018,Vehicle Miles 2019,Vehicle Miles 2020,Vehicle Miles 2021,Vehicle Miles 2022,Vehicle Miles 2023
0,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,PT,Bus,8335875,8511613,3913186,4022799,4968632,3582380
1,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,TN,Bus,0,0,0,0,0,529335
2,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,TX,Bus,1675832,2052404,905250,934957,1461592,1089948
3,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,49706,52362,35948,49606,51236,35426
4,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",LR,DO,Rail,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2255,99423,City of Glendale,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",MB,PT,Bus,720541,720907,735647,864334,868128,581234
2256,99424,City of Pasadena,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,PT,Bus,242653,251734,157970,150265,136655,122088
2257,99424,City of Pasadena,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",MB,PT,Bus,708046,722336,734910,723915,701730,445970
2258,99425,Pomona Valley Transportation Authority,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,PT,Bus,254522,255161,108487,241948,259825,162906
2259,99425,Pomona Valley Transportation Authority,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,TX,Bus,312530,269466,142583,99031,97682,72573

In [22]:
# Assuming these columns are common for merging
columns_to_merge_on = ['NTD ID', 'Agency', 'Status', 'Reporter Type', 'UACE CD', 'UZA Name', 'Mode', 'TOS', '3 Mode']

# Merge the DataFrames on the specified columns
df_transit = df_trips.merge(df_vehicle_miles, on=columns_to_merge_on)

In [23]:
df_transit

,NTD ID,Agency,Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,Trips 2018,Trips 2019,Trips 2020,Trips 2021,Trips 2022,Trips 2023,Vehicle Miles 2018,Vehicle Miles 2019,Vehicle Miles 2020,Vehicle Miles 2021,Vehicle Miles 2022,Vehicle Miles 2023
0,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,PT,Bus,883312,887915,455391,468104,552215,400306,8335875,8511613,3913186,4022799,4968632,3582380
1,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,TN,Bus,0,0,0,0,0,150541,0,0,0,0,0,529335
2,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",DR,TX,Bus,143747,177791,86460,88944,110794,82622,1675832,2052404,905250,934957,1461592,1089948
3,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,664365,701608,146930,286843,400407,286634,49706,52362,35948,49606,51236,35426
4,1,King County Department of Metro Transit,Active,Full Reporter: Operating,80389,"Seattle--Tacoma, WA",LR,DO,Rail,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2255,99423,City of Glendale,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",MB,PT,Bus,1431136,1414940,529112,418715,624155,509462,720541,720907,735647,864334,868128,581234
2256,99424,City of Pasadena,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,PT,Bus,86218,90957,38581,35436,38412,37337,242653,251734,157970,150265,136655,122088
2257,99424,City of Pasadena,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",MB,PT,Bus,1508413,1526844,957115,931575,1139100,710151,708046,722336,734910,723915,701730,445970
2258,99425,Pomona Valley Transportation Authority,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,PT,Bus,84088,84110,30654,41567,57862,45972,254522,255161,108487,241948,259825,162906
2259,99425,Pomona Valley Transportation Authority,Active,Full Reporter: Operating,51445,"Los Angeles--Long Beach--Anaheim, CA",DR,TX,Bus,68805,63067,37262,23044,18194,13090,312530,269466,142583,99031,97682,72573

In [24]:
# Create a new dataFrame by grouping and summing the required columns
df_transit_sum = df_transit.groupby(['UZA Name', 'UACE CD']).agg({
    'Trips 2018': 'sum',
    'Trips 2019': 'sum',
    'Trips 2020': 'sum',
    'Trips 2021': 'sum',
    'Trips 2022': 'sum',
    'Trips 2023': 'sum',
    'Vehicle Miles 2018': 'sum',
    'Vehicle Miles 2019': 'sum',
    'Vehicle Miles 2020': 'sum',
    'Vehicle Miles 2021': 'sum',
    'Vehicle Miles 2022': 'sum',
    'Vehicle Miles 2023': 'sum'
})

# Reset the index to make '3 Mode', 'UACE CD' and 'UZA Name' regular columns
df_transit_sum.reset_index(inplace=True)

In [25]:

# Melt the DataFrame to create a 'Year' column
melted_df = pd.melt(df_transit_sum, id_vars=['UZA Name', 'UACE CD'], var_name='Year', value_name='Value')

# Separate 'Trips' and 'Vehicle Miles' into two new columns
melted_df['Category'] = melted_df['Year'].str.extract(r'(Trips|Vehicle Miles)')
melted_df['Year'] = melted_df['Year'].str.extract(r'(\d{4})')

# Pivot the DataFrame to have separate columns for 'Trips' and 'Vehicle Miles'
df_transit_pivot = melted_df.pivot_table(index=['UZA Name', 'UACE CD', 'Year'], columns='Category', values='Value').reset_index()

# Rename the columns for clarity
df_transit_pivot.columns.name = None

In [26]:
df_transit_pivot.shape

(2340, 5)

In [27]:
df_transit_pivot.rename(columns = {'UACE CD': 'UACE Code'}, inplace = True)

In [28]:
df_transit_pivot['UACE Code'] = df_transit_pivot['UACE Code'].astype(str).str.zfill(5)

In [29]:
df_transit_pivot.dtypes

UZA Name         object
UACE Code        object
Year             object
Trips             int64
Vehicle Miles     int64
dtype: object

In [30]:
df_transit_pivot['Year'] = pd.to_numeric(df_transit_pivot['Year'], errors='coerce')

#### Check for Missing Values

In [31]:
# Check for missing values

df_transit_pivot.isnull().sum()

UZA Name         0
UACE Code        0
Year             0
Trips            0
Vehicle Miles    0
dtype: int64

In [32]:
# Check for missing values

df_transit_pivot.isnull().sum()

UZA Name         0
UACE Code        0
Year             0
Trips            0
Vehicle Miles    0
dtype: int64

#### Check for Duplicates

In [33]:
# Find duplicates

df_transit_pivot_dups = df_transit_pivot[df_transit_pivot.duplicated()]

In [34]:
df_transit_pivot_dups.shape # No duplicates!

(0, 5)

#### Check for Mixed-Type Data:

In [35]:
for col in df_transit_pivot.columns.tolist():
      weird = (df_transit_pivot[[col]].applymap(type) != df_transit_pivot[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df_transit_pivot[weird]) > 0:
        print (col)
        
# No mixed-type columns

## 4. Combine commuter and transit datasets

In [36]:
# Merge df_commuter and df_transit on 'UACE Code' and 'Year' columns
df_commuter_transit = df_transit_pivot.merge(df_commuter, on=['UACE Code', 'Year'], how='inner')

In [37]:
# Check merge using Seattle urban area
df_commuter_transit[df_commuter_transit['UACE Code'] == 80389]

Empty DataFrame
Columns: [UZA Name, UACE Code, Year, Trips, Vehicle Miles, Geography, Geographic Area Name, Commute by Car, Truck, or Van, Commute by Drove alone, Commute by Carpooled, Commute by 2-person Carpool, Commute by 3-person Carpool, Commute by 4-or-more-person Carpool, Average Number of Workers per Car, Commute by Public Transportation, Commute by Walking, Commute by Bicycle, Commute by Taxicab, Motorcycle, or Other means, Commute by Work from Home, Commute Time <10 Minutes, Commute Time 10 to 14 Minutes, Commute Time 15 to 19 Minutes, Commute Time 20 to 24 Minutes, Commute Time 25 to 29 Minutes, Commute Time 30 to 34 Minutes, Commute Time 35 to 44 Minutes, Commute Time 45 to 59 Minutes, Commute Time >60 Minutes, Mean Commute Time, Depart Time 12:00 a.m. to 4:59 a.m., Depart Time 5:00 a.m. to 5:29 a.m., Depart Time 5:30 a.m. to 5:59 a.m., Depart Time 6:00 a.m. to 6:29 a.m., Depart Time 6:30 a.m. to 6:59 a.m., Depart Time 7:00 a.m. to 7:29 a.m., Depart Time 7:30 a.m. to 7:59 a.m., Depart Time 8:00 a.m. to 8:29 a.m., Depart Time 8:30 a.m. to 8:59 a.m., Depart Time 9:00 a.m. to 11:59 p.m., Workers 16 Years and Over in Households, Households with 0 Vehicles available, Households with 1 Vehicle Available, Households with 2 Vehicles Available, Households with 3 or More Vehicles Available, Worked in State of Residence, Worked in County of Residence, Worked Outside County of Residence, Worked Outside State of Residence, Living in a Place, Worked in Place of Residence, Worked Outside Place of Residence, Not living in a place]
Index: []

In [38]:
df_commuter_transit.drop(columns = ['Geography', 'Geographic Area Name'], inplace = True)

In [39]:
# Create a new column 'Average Number of Vehicles per Household'

# Calculate the weighted average of vehicles per household and impute as 'Average Number of Vehicles per Household' column
df_commuter_transit['Average Number of Vehicles per Household'] = (
    (0 * df_commuter_transit['Households with 0 Vehicles available']/100) +
    (1 * df_commuter_transit['Households with 1 Vehicle Available']/100) +
    (2 * df_commuter_transit['Households with 2 Vehicles Available']/100) +
    (3 * df_commuter_transit['Households with 3 or More Vehicles Available']/100)
)

In [41]:
df_commuter_transit

,UZA Name,UACE Code,Year,Trips,Vehicle Miles,"Commute by Car, Truck, or Van",Commute by Drove alone,Commute by Carpooled,Commute by 2-person Carpool,Commute by 3-person Carpool,Commute by 4-or-more-person Carpool,Average Number of Workers per Car,Commute by Public Transportation,Commute by Walking,Commute by Bicycle,"Commute by Taxicab, Motorcycle, or Other means",Commute by Work from Home,Commute Time <10 Minutes,Commute Time 10 to 14 Minutes,Commute Time 15 to 19 Minutes,Commute Time 20 to 24 Minutes,Commute Time 25 to 29 Minutes,Commute Time 30 to 34 Minutes,Commute Time 35 to 44 Minutes,Commute Time 45 to 59 Minutes,Commute Time >60 Minutes,Mean Commute Time,Depart Time 12:00 a.m. to 4:59 a.m.,Depart Time 5:00 a.m. to 5:29 a.m.,Depart Time 5:30 a.m. to 5:59 a.m.,Depart Time 6:00 a.m. to 6:29 a.m.,Depart Time 6:30 a.m. to 6:59 a.m.,Depart Time 7:00 a.m. to 7:29 a.m.,Depart Time 7:30 a.m. to 7:59 a.m.,Depart Time 8:00 a.m. to 8:29 a.m.,Depart Time 8:30 a.m. to 8:59 a.m.,Depart Time 9:00 a.m. to 11:59 p.m.,Workers 16 Years and Over in Households,Households with 0 Vehicles available,Households with 1 Vehicle Available,Households with 2 Vehicles Available,Households with 3 or More Vehicles Available,Worked in State of Residence,Worked in County of Residence,Worked Outside County of Residence,Worked Outside State of Residence,Living in a Place,Worked in Place of Residence,Worked Outside Place of Residence,Not living in a place,Average Number of Vehicles per Household
0,"Abilene, TX",00280,2018,0,0,91.3,76.7,14.6,10.3,2.3,2.0,1.10,0.1,1.6,0.0,1.2,5.7,24.8,29.7,26.2,11.0,0.5,3.4,0.7,1.2,2.6,15.2,5.5,2.4,5.0,4.1,9.1,13.7,20.0,8.4,6.2,25.4,54675,2.9,27.3,46.2,23.6,99.8,94.0,5.8,0.2,99.6,88.7,10.9,0.4,1.905
1,"Abilene, TX",00280,2019,0,0,90.6,79.9,10.7,8.2,1.9,0.6,1.07,0.2,1.9,0.6,1.0,5.6,24.9,25.4,29.6,11.8,1.4,3.3,0.6,1.7,1.3,14.6,5.0,2.2,4.0,6.1,9.3,12.2,18.2,10.9,6.6,25.3,54753,2.4,20.6,50.3,26.7,99.6,95.8,3.8,0.4,99.6,90.7,8.9,0.4,2.013
2,"Abilene, TX",00280,2020,0,0,89.8,78.8,11.0,8.3,1.5,1.2,1.07,0.8,2.4,0.2,0.7,6.1,24.4,27.7,26.3,11.0,1.4,3.7,0.8,1.3,3.3,16.0,5.8,2.2,4.6,4.9,9.5,12.4,19.8,9.1,5.6,26.3,54839,2.7,23.3,48.3,25.7,99.8,93.5,6.3,0.2,99.4,88.6,10.8,0.6,1.970
3,"Abilene, TX",00280,2022,0,0,87.7,77.8,9.9,7.3,1.6,0.9,1.07,0.9,2.1,0.0,1.0,8.4,21.1,28.6,27.1,14.3,2.7,2.3,1.2,1.2,1.6,14.9,3.4,2.4,3.6,6.5,13.2,12.2,19.9,8.2,6.1,24.6,59559,2.9,21.8,47.8,27.5,97.3,93.9,3.3,2.7,99.8,90.8,9.0,0.2,1.999
4,"Akron, OH",00766,2018,6365983,7530163,90.1,82.4,7.7,5.5,1.3,0.8,1.05,2.0,2.0,0.3,0.6,5.1,12.5,15.2,16.4,17.9,9.4,12.1,6.3,6.1,4.2,23.1,3.4,2.9,5.3,9.1,11.5,14.6,11.6,10.2,5.0,26.4,272448,4.0,19.6,45.2,31.2,99.4,70.9,28.5,0.6,84.9,26.4,58.5,15.1,2.036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,"Yuba City, CA",97939,2022,481388,965750,89.6,75.6,14.0,8.2,1.2,4.6,1.10,0.3,1.1,0.8,1.6,6.6,14.0,15.3,12.0,8.5,2.2,10.5,9.1,15.9,12.4,31.0,9.5,10.6,5.4,9.3,10.3,11.2,11.3,9.7,3.0,19.7,53027,4.0,12.6,34.2,49.1,99.4,48.1,51.3,0.6,93.4,30.0,63.3,6.6,2.283
1592,"Yuma, AZ--CA",98020,2018,527878,1330228,93.6,81.0,12.6,8.5,2.4,1.6,1.08,0.7,2.1,0.1,0.9,2.6,23.6,21.3,22.2,14.5,4.5,6.7,1.5,2.9,2.7,16.8,6.8,5.3,5.7,11.4,10.7,11.5,12.6,6.1,4.3,25.8,51084,1.7,21.6,40.7,36.0,95.7,95.0,0.7,4.3,92.9,63.3,29.6,7.1,2.110
1593,"Yuma, AZ--CA",98020,2019,540953,1234866,91.8,79.3,12.5,9.5,1.5,1.4,1.08,0.4,2.5,0.5,1.0,3.8,20.5,23.1,21.5,15.4,4.6,6.3,3.1,3.2,2.3,17.5,8.8,7.2,7.0,6.6,7.6,11.3,17.2,8.5,2.7,23.1,49472,3.1,21.4,39.5,35.9,95.9,94.3,1.6,4.1,92.0,61.5,30.5,8.0,2.081
1594,"Yuma, AZ--CA",98020,2020,318884,1056634,91.5,79.1,12.4,9.4,1.4,1.5,1.08,0.6,2.3,0.4,1.4,3.7,20.5,22.3,22.3,14.3,5.4,7.7,2.8,2.0,2.7,17.5,8.1,5.7,6.5,8.6,8.0,11.4,15.4,8.5,3.8,23.9,51138,2.0,20.3,41.8,35.9,95.0,94.0,1.0,5.0,92.8,60.1,32.7,7.2,2.116
1595,"Yuma, AZ--CA",98020,2022,392797,1289509,87.0,77.8,9.2,5.8,1.7,1.8,1.07,0.2,2.3,0.3,1.0,9.1,14.8,19.4,22.8,19.4,2.6,11.4,2.6,3.6,3.3,19.4,9.0,9.8,9.1,8.8,10.7,13.3,8.8,5.0,2.3,23.1,51855,2.9,19.9,42.2,35.0,92.1,91.7,0.4,7.9,95.0,58.9,36.1,5.0,2.093

## 5. Export combined commuter and transit dataframe

In [44]:
# Export combined dataframe into csv file in transformed data folder as 'commuter_transit_2018_to_2022.csv'
df_commuter_transit.to_csv(os.path.join(path, 'Datasets', 'Transformed Data', 'commuter_transit_2018_to_2022.csv'), index=False)